### ISSUE TITLE
Support for serde serialize / deserialize 

### ISSUE THREAD

**Issue by rohitjoshi** [unrelentingtech/secstr#25]
It would be good to implement support for serialize and deserialize using serde which allows to read sensitive data from json/toml config file as I am defining SecUtf8 type for sensitive field in a structure. These secrets are populated at runtime but in the config defined as an empty string.

```
 db_user: SecUtf8,
 db_password: SecUtf8,
```

**Comment by unrelentingtech** [comment]
Uh, that was always here. It's literally mentioned in the readme. Just enable the `serde` cargo feature.
