### ISSUE TITLE
Deref Implementations

### ISSUE THREAD

**Issue by Alch-Emi** [unrelentingtech/secstr#26]
Hello!

I noticed that most types in `secstr` don't implement `Deref`, even when their non-secure counterparts do.  Since `Deref` is a pretty handy feature for writing concise and readable code, I was wondering if this was a deliberate choice, or if it just hasn't been done yet.  If it just needs doing, I would be more than happy to write the PR myself, but I didn't want to presume that it was unintentional.

**Comment by unrelentingtech** [comment]
Yes, it's deliberate that you need to call `.unsecure()` to access the contents. The name makes it easy to find all the places where you deal with raw secrets in the code. (Well… other than serde serializations.)

Also the [docs](https://doc.rust-lang.org/std/ops/trait.Deref.html) say

> Deref should only be implemented for smart pointers

And none of the types here are smart pointers, they're little wrappers.
